services:
  # Your server
  server:
    build:
    # use root as context to reed common folder
      context: .
      # use server Dockerfile
      dockerfile: server/Dockerfile
    ports:
        # HOST_PORT (from .env) : CONTAINER_PORT (Fixed 3000)
        # added 127.0.0.1 to avoid exposing the port to the whole network, only to the host machine
      - "127.0.0.1:${PORT}:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      # enables live changes
      - ./server:/usr/src/app/server 
      - ./common:/usr/src/app/common
      # ignores node_modules to avoid conflicts between host and container
      - /usr/src/app/node_modules
      - /usr/src/app/server/node_modules
      
    env_file:
     - .env